# Generated by Django 5.0.8 on 2024-09-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_youtube_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_publish', 'Can Publish Articles'), ('can_edit', 'Can Edit Articles'), ('can_read', 'Can Read Articles')]},
        ),
    ]
