# Generated by Django 5.0.7 on 2024-09-29 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.subcategory'),
        ),
    ]
