# Generated by Django 5.0.7 on 2024-10-02 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.EmailField(default='no-reply@example.com', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
